server:
  port: 8050
spring:
 application:
  name: feign
eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka/
   fetch-registry: true
 instance:
   prefer-ip-address: true
feign:
   hystrix:
      enable: true
